secret step added

diff --git a/.github/workflows/frontend_CI.yml b/.github/workflows/frontend_CI.yml
--- a/.github/workflows/frontend_CI.yml
+++ b/.github/workflows/frontend_CI.yml
@@ -35,6 +35,15 @@ jobs:
       - name: build the application
         run: npm run build
 
+      - name: Debug Secrets
+        run: |
+              if [ -n "${{ secrets.SONARQUBE_TOKEN }}" ]; then
+              echo "SONARQUBE_TOKEN exists"
+              else
+             echo "SONARQUBE_TOKEN missing"
+             exit 1
+              fi
+
       - name: SonarQube code analysis
         uses: SonarSource/sonarqube-scan-action@v5
         env:
